language: node_js
node_js:
  - '4'
  - '5'
  - '6'
  - '7'
  - 'node'

before_install:
  - npm install -g typescript@2.0.2
after_success:
  - npm run semantic-release
  - npm run test:travis
  - "test -e ./coverage/lcov.info && npm install coveralls@2 remap-istanbul@0.6.4 && ./node_modules/.bin/remap-istanbul -i ./coverage/coverage.json -t lcovonly | coveralls"

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
sudo: false
