language: node_js
notifications:
  email: false
node_js:
  - '4'
  - '5'
  - '6'
  - '7'
  - 'node'
after_success:
  - npm run semantic-release
  - npm run coveralls:travis
  - sh ./afterpublish.sh
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
sudo: false